server:
  port: 8762

spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared



#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/JiayingZhong/orderingsystem_config.git
#          label: master



